import { test, expect } from "@playwright/test";

// US2 visual parity (SC-006): snapshot the Frontegg embedded sign-in box on the
// MCP /login page and compare against the main-app baseline.
//
// The embedded box only renders against a real/sandbox Frontegg tenant (it
// fetches the enabled social-login configuration), so this test is gated on the
// same sandbox env the @e2e suite uses and is CI/owner-run. The baseline is
// generated by the project owner against the sandbox (Constitution: live
// rendering is owner-verified). It is a no-op locally without the env.

const SANDBOX_READY =
    !!process.env.FRONTEGG_E2E_SANDBOX_EMAIL &&
    !!process.env.NEXT_PUBLIC_FRONTEGG_BASE_URL;

test.describe("@visual embedded login box", () => {
    test.skip(
        !SANDBOX_READY,
        "Requires a Frontegg sandbox (FRONTEGG_E2E_SANDBOX_* + NEXT_PUBLIC_FRONTEGG_BASE_URL)",
    );

    test("renders the embedded box with Google + email/password", async ({ page }) => {
        await page.goto("/login?pending=okm_visual_test_pending_code");

        // The Frontegg box mounts its own form; wait for an email field and the
        // Google social button to appear before snapshotting.
        await expect(page.getByRole("button", { name: /google/i })).toBeVisible({
            timeout: 15_000,
        });

        await expect(page).toHaveScreenshot("login-box.png", {
            maxDiffPixelRatio: 0.02,
        });
    });
});
