"""RFC 7591 Dynamic Client Registration endpoint.

**Rewritten 2026-05-16 (OAuth Proxy redesign) and 2026-05-18 (stateless
DCR + PKCE-upstream).** The previous version forwarded registrations to
Frontegg's Applications-create management API. Now: ``/register``
synthesizes a stateless, HMAC-signed client_id via
``OAuthStateStore.register_client`` — no Frontegg roundtrip per client,
no server-side storage of registrations.

Frontegg holds exactly one Application (identified by `FRONTEGG_CLIENT_ID`;
the OAuth Proxy authenticates to it as a public PKCE client, no
client_secret). MCP-client registrations and their redirect URIs live
entirely inside the signed client_id string. See
``contracts/mcp-auth-contract.md`` for the architectural rationale.
"""

from __future__ import annotations

import json
import logging
import time

from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route

from src.auth.oauth_state import OAuthStateStore


_logger = logging.getLogger(__name__)


def build_dcr_app(store: OAuthStateStore) -> Starlette:
    """Return a Starlette app exposing ``POST /register`` (RFC 7591).

    Registrations are stored in the supplied ``OAuthStateStore``. The
    response is the standard RFC 7591 shape; ``client_id`` is generated by
    us (opaque, ~256 bits), and ``client_secret`` is omitted (all MCP
    clients are public OAuth clients per PKCE).
    """

    async def _register(request: Request) -> JSONResponse:
        try:
            body = await request.json()
        except (ValueError, json.JSONDecodeError):
            return JSONResponse(
                {
                    "error": "invalid_client_metadata",
                    "error_description": "Malformed JSON body",
                },
                status_code=400,
            )

        if not isinstance(body, dict):
            return JSONResponse(
                {
                    "error": "invalid_client_metadata",
                    "error_description": "Body must be an object",
                },
                status_code=400,
            )

        redirect_uris = body.get("redirect_uris")
        if not isinstance(redirect_uris, list) or not redirect_uris:
            return JSONResponse(
                {
                    "error": "invalid_redirect_uri",
                    "error_description": (
                        "redirect_uris is required and must be a non-empty list"
                    ),
                },
                status_code=400,
            )

        # Reject obviously malformed entries early.
        for uri in redirect_uris:
            if not isinstance(uri, str) or not uri:
                return JSONResponse(
                    {
                        "error": "invalid_redirect_uri",
                        "error_description": "redirect_uris must be a list of non-empty strings",
                    },
                    status_code=400,
                )

        client_name = body.get("client_name", "MCP Client")
        scope = body.get("scope", "okareo:use")
        token_endpoint_auth_method = body.get(
            "token_endpoint_auth_method", "none"
        )

        record = await store.register_client(
            client_name=client_name,
            redirect_uris=tuple(redirect_uris),
            token_endpoint_auth_method=token_endpoint_auth_method,
            scope=scope,
        )

        rfc7591 = {
            "client_id": record.client_id,
            "client_id_issued_at": int(time.time()),
            "client_secret_expires_at": 0,
            "redirect_uris": list(record.redirect_uris),
            "token_endpoint_auth_method": record.token_endpoint_auth_method,
            "grant_types": body.get(
                "grant_types", ["authorization_code", "refresh_token"]
            ),
            "response_types": body.get("response_types", ["code"]),
            "scope": scope,
            "client_name": client_name,
        }
        return JSONResponse(rfc7591, status_code=201)

    return Starlette(
        routes=[Route("/register", endpoint=_register, methods=["POST"])]
    )
